In [1]:
 import numpy as np

# Arrays

In [4]:
arr = np.array([3, "a", 85, "n", "nd"])
# A basic array created with a list that contains different data types such as strings and integers

In [5]:
arr

array(['3', 'a', '85', 'n', 'nd'], dtype='<U11')

In [8]:
type(arr)
# Type of our array 'arr'

numpy.ndarray

In [9]:
arr2 = np.array([3, 5, 3.9, 7])

In [11]:
arr2
# All the integers turn into float too because we have a float number in the list

array([3. , 5. , 3.9, 7. ])

In [12]:
arr3 = np.array([3, 5, 3.9, "md", "f", 7])

In [14]:
arr3
# Now all of the data types turned into string form because there is a string added to the list

array(['3', '5', '3.9', 'md', 'f', '7'], dtype='<U32')

In [15]:
arr4 = np.array([3, 6, 3.4, 7.9, 5], dtype= "int32")

In [17]:
arr4
# All the float values turned into integers because we changed the data type

array([3, 6, 3, 7, 5])

In [20]:
arr5 = np.array([3, 6, 3.4, 7.9, 5], dtype= "str")

In [22]:
arr5
# Now they are all in string form

array(['3', '6', '3.4', '7.9', '5'], dtype='<U3')

In [24]:
arr6 = np.array(["a", 6, "nı", 7.9, 5], dtype= "int32")
# But unfortunately we can't turn string to an integer

ValueError: invalid literal for int() with base 10: 'a'

## Zero Arrays (zero() function)

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10, dtype= "str")
# Creates ten empty strings

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [31]:
np.zeros(10, dtype= "int32")
# Creates ten empty strings

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros([2,5,5], dtype="int32")

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

## full() Function

In [37]:
np.full(2,5)

array([5, 5])

In [36]:
np.full((2,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [38]:
np.full((2,5), 3, dtype="str")

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

In [39]:
np.full((2,5), "3", dtype="str")

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

## Consecutive Numbers (arange() Function)

In [41]:
np.arange(2,6)

array([2, 3, 4, 5])

In [42]:
np.arange(2,6,2)

array([2, 4])

In [45]:
np.arange(2,6,-2)
# Doesn't print anything because the start point of list is already smaller than end point

array([], dtype=int32)

In [46]:
np.arange(6,2,-2)

array([6, 4])

## Spacing (linspace() Function)

In [66]:
np.linspace(3,6,3)
# Creates middle points between 3 and 6 in float type

array([3. , 4.5, 6. ])

In [67]:
np.linspace(3,4,3, endpoint=False)
#Doesn't include the endpoint

array([3.        , 3.33333333, 3.66666667])

In [68]:
np.linspace(3.2, 4.4, 3)
# Works for float datas too

array([3.2, 3.8, 4.4])

## Normal Distribution

In [71]:
np.random.normal(0, 3, (4,5))
# (mean, std, array size)

array([[-3.45414411,  1.38409024, -3.51203705, -3.51413392,  1.10412924],
       [-1.24270413,  2.537997  , -0.27558317, -3.50107198, -1.10457978],
       [-0.95404842,  5.28464745, -0.95862866,  8.73162184, -2.29705844],
       [ 0.43340347, -1.98950918,  3.26959406,  4.71961799,  2.4361533 ]])

In [72]:
np.random.normal(10, 1, (4,5))

array([[ 9.19166537,  8.8698226 ,  7.91132544,  8.58087311, 10.87081791],
       [10.02395497,  9.26069823, 11.53142247,  7.07555794,  9.86421511],
       [11.79812528, 11.38664158,  9.7799666 ,  9.7106613 ,  9.2936777 ],
       [11.70871977, 10.91674113, 10.21915406, 10.24009876, 10.9431344 ]])

## Creating Arrays With Random Integers

In [86]:
np.random.randint(1, 10)
# Get a random value between 1 and 10

9

In [87]:
np.random.randint(1, 10, (4,5))
# Create a 4,5 matrix with random values between 1 and 10

array([[1, 3, 3, 7, 9],
       [5, 9, 7, 4, 9],
       [9, 6, 5, 1, 9],
       [4, 2, 8, 2, 5]])

In [88]:
np.random.randint(1, 10, (3,4,5))
# Create 3 of this

array([[[6, 9, 6, 9, 3],
        [1, 8, 8, 8, 2],
        [4, 8, 6, 7, 8],
        [4, 2, 1, 4, 9]],

       [[7, 5, 1, 7, 7],
        [8, 4, 3, 8, 5],
        [4, 9, 9, 9, 4],
        [4, 7, 4, 4, 5]],

       [[3, 1, 4, 2, 1],
        [5, 8, 3, 5, 1],
        [4, 7, 5, 3, 4],
        [3, 5, 7, 3, 9]]])

In [89]:
d= {}

for _ in range(1000):
    val= np.random.randint(1,11)

    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [92]:
d # Generate random values between 1 and 11 (not included) and observe how many times we get the number 

{2: 101, 6: 105, 5: 109, 3: 108, 9: 89, 10: 97, 4: 97, 7: 90, 8: 107, 1: 97}

## Identity Matrix (eye() Function)

In [96]:
np.eye(4,5)
# Creates a 4 row and 5 column matrix and fills it with 1's in diagonal direction

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [103]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Array Operations

In [104]:
x= [2,5,8,6]
y= [5,1,4,3]

In [109]:
y * 3
# Prints y list 3 times in the same container

[5, 1, 4, 3, 5, 1, 4, 3, 5, 1, 4, 3]

In [112]:
y + y + y
# Same operation like the multiplication

[5, 1, 4, 3, 5, 1, 4, 3, 5, 1, 4, 3]

In [117]:
a = np.array([5,2,7])
b= np.array([3,1,9])

a * b
# Multiply the values in the same index (maximum index should be the same)
#(5*3, 2*1, 7*9)

array([15,  2, 63])

In [119]:
a + b
# Sums the same indeced values

array([ 8,  3, 16])

In [120]:
c = [3, 5, 8]
d = [2, 1, 5]

In [122]:
c + d
# Does concatenation to the list ones (not arrays)

[3, 5, 8, 2, 1, 5]

In [127]:
b = b * 2 # Update the values

In [128]:
b  

array([24,  8, 72])

## Array Attributes

In [133]:
k = np.zeros((3,4))

print(k)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [134]:
k.shape

(3, 4)

In [136]:
l = np.zeros((2,3,4))

print(l)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [137]:
l.shape

(2, 3, 4)

In [141]:
l.ndim
# Print how many dimension the array has

3

In [142]:
k.ndim

2

In [144]:
k.size
# row * column

12

In [145]:
k.dtype

dtype('float64')

## Reshaping

In [150]:
m = np.arange(2,8)

print(m)

[2 3 4 5 6 7]


In [156]:
m.ndim

1

In [157]:
m.reshape(2,3)
# Reshape the array into 2 rows by 3 index for each

array([[2, 3, 4],
       [5, 6, 7]])

In [159]:
m.reshape(2,3).ndim
# Observe the new dimension quantity

2

In [163]:
m.reshape(-1, 2)
# make the row number 'size / 2'

array([[2, 3],
       [4, 5],
       [6, 7]])

In [164]:
m.reshape(-1, 3)
# make the row number 'size / 3'

array([[2, 3, 4],
       [5, 6, 7]])

In [168]:
m[np.newaxis, :]
# Added columns for every index and made it a 1 row matrix

array([[2, 3, 4, 5, 6, 7]])

In [172]:
m[:, np.newaxis]
# Row number is increased now and there is just 1 column

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

Here are the same results with "None" instead of ":"

In [175]:
m[np.newaxis, None]

array([[[2, 3, 4, 5, 6, 7]]])

In [176]:
m[None, np.newaxis]

array([[[2, 3, 4, 5, 6, 7]]])